#ifndef __BK7258_WIFI_GLUE_SYS_TYPES_H
#define __BK7258_WIFI_GLUE_SYS_TYPES_H

#include <stdint.h>
#include <bk7258_memorymap.h>

typedef enum
{
  POWER_MODULE_NAME_MEM1 = 0, POWER_MODULE_NAME_MEM2,
  POWER_MODULE_NAME_MEM3, POWER_MODULE_NAME_ENCP, POWER_MODULE_NAME_BAKP,
  POWER_MODULE_NAME_AHBP, POWER_MODULE_NAME_AUDP, POWER_MODULE_NAME_VIDP,
  POWER_MODULE_NAME_BTSP, POWER_MODULE_NAME_WIFIP_MAC,
  POWER_MODULE_NAME_WIFI_PHY, POWER_MODULE_NAME_MEM0,
  POWER_MODULE_NAME_MEM4, POWER_MODULE_NAME_OFDM, POWER_MODULE_NAME_MEM5,
  POWER_MODULE_NAME_ROM_PGEN, POWER_MODULE_NAME_TCM1_PGEN,
  POWER_MODULE_NAME_CPU1, POWER_MODULE_NAME_APP, POWER_MODULE_NAME_CPU2,
  POWER_MODULE_NAME_NONE
} power_module_name_t;

typedef enum
{
  POWER_MODULE_STATE_ON = 0, POWER_MODULE_STATE_OFF,
  POWER_MODULE_STATE_NONE
} power_module_state_t;

typedef enum
{
  WAKEUP_SOURCE_INT_GPIO = 0, WAKEUP_SOURCE_INT_RTC,
  WAKEUP_SOURCE_INT_WIFI, WAKEUP_SOURCE_INT_BT,
  WAKEUP_SOURCE_INT_USBPLUG, WAKEUP_SOURCE_INT_TOUCHED,
  WAKEUP_SOURCE_INT_NONE
} wakeup_source_t;

#define WIFI_MODEM_EN                 BK7258_SYS_WIFI_MODEM_INT_EN
#define WIFI_MODEM_RC_EN              BK7258_SYS_WIFI_MODEM_RC_INT_EN
#define WIFI_MAC_TX_RX_TIMER_INT_BIT  BK7258_SYS_WIFI_MAC_TXRX_TIMER_INT_EN
#define WIFI_MAC_TX_RX_MISC_INT_BIT   BK7258_SYS_WIFI_MAC_TXRX_MISC_INT_EN
#define WIFI_MAC_RX_TRIGGER_INT_BIT   BK7258_SYS_WIFI_MAC_RX_TRIGGER_INT_EN
#define WIFI_MAC_TX_TRIGGER_INT_BIT   BK7258_SYS_WIFI_MAC_TX_TRIGGER_INT_EN
#define WIFI_MAC_PORT_TRIGGER_INT_BIT BK7258_SYS_WIFI_MAC_PROT_TRIGGER_INT_EN
#define WIFI_MAC_GEN_INT_BIT          BK7258_SYS_WIFI_MAC_GEN_INT_EN
#define WIFI_MAC_WAKEUP_INT_BIT       BK7258_SYS_WIFI_MAC_WAKEUP_INT_EN

#endif
